### ISSUE TITLE
Suggest builtin snippets

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/feel-editor#14]
__Is your feature request related to a problem? Please describe__

If conditions and for loops in FEEL are very different from the widely used languages. It is hard for new developers to understand the syntax

__Describe the solution you'd like__

Suggest code snippts with placeholders that create the correct syntax for the user

__Describe alternatives you've considered__

__Additional context__

related to https://github.com/bpmn-io/feel-editor/issues/11

**Comment by nikku** [comment]
Closed via #11

**Comment by marstamm** [comment]
closed with https://github.com/bpmn-io/feel-editor/pull/21
