### ISSUE TITLE
Support multiline strings

### ISSUE THREAD

**Issue by camundacon2022-connectors** [bpmn-io/feel-editor#17]
__Is your feature request related to a problem? Please describe__

The feel-scala engine, used in Zeebe, supports multiline strings. They can just be declared with double quotes, similar to single-line strings. However, the FEEL editor marks those multiline strings as erroneous and does not support syntax highlighting for them (it expects strings to end latest at the end of line). This misleads users thinking that multiline strings are not supported.

![Bildschirmfoto 2022-09-06 um 18 12 04](https://user-images.githubusercontent.com/112961023/188688295-ec050c7e-11cf-4af2-8b34-f920cf482fa7.png)

A few APIs expect unescaped line break characters for text bodies (instead of "/n" or "/r/n", such as the Github issue API. Multiline strings are mandatory here to serve those APIs with multiline text bodies.

__Describe the solution you'd like__

The parser recognizes multiline strings correctly and the editor applies correct syntax highlighting, without throwing an error.

__Describe alternatives you've considered__

__Additional context__

**Comment by christian-konrad** [comment]
Oops, created it with the wrong account.

**Comment by marstamm** [comment]
As long as we have it reported 😄

**Comment by nikku** [comment]
We'd need to verify against the DMN FEEL spec if multi-line strings are a thing. If that is the case this must be fixed in our parse tooling.

**Comment by marstamm** [comment]
So if I read this correctly a a String is defined as a list of character **without** vertical Space

![image](https://user-images.githubusercontent.com/21984219/191908728-04b55cab-b20f-48d3-853f-70ce8f6ca455.png)

and vertical Space is Line Feed, Line Tab, Form Feed, Carriage Return
![image](https://user-images.githubusercontent.com/21984219/191908811-209462d1-df1e-468d-bd72-59b900b76aa3.png)

So Multi-Line Strings are not part of the Spec

**Comment by nikku** [comment]
Closing this as multi-line strings are not covered by the BPMN spec (cf. https://github.com/bpmn-io/feel-editor/issues/17#issuecomment-1255869673, [double check](https://camunda.slack.com/archives/C01QYD808A3/p1663918405714019?thread_ts=1663917376.169139&cid=C01QYD808A3)).
