### ISSUE TITLE
Add support for scrolling

### ISSUE THREAD

**Issue by CatalinaMoisuc** [bpmn-io/feel-editor#19]
__Is your feature request related to a problem? Please describe__

Currently the message body of the SQS connector does not have a scroll bar(horizontally or vertically) and hence scrolling through a long message to edit or update is difficult 

__Describe the solution you'd like__

Adding scroll bars vertically and horizontally based on the size of the text could be useful for the user to edit or update the message body

https://user-images.githubusercontent.com/25924333/189159679-96498280-2368-4389-b820-bb4a92422c94.mp4

In addition to the scrolling, we could support also auto formatting so the text is split on multiple lines.

__Describe alternatives you've considered__

We could follow the same structure as it is in "Documentation" section in the properties panel or like the message body we have in Send grid email connector

https://user-images.githubusercontent.com/25924333/189159635-f7092766-3e02-4aec-b6c9-205eff1c1773.mp4

__Additional context__

**Comment by pinussilvestrus** [comment]
Makes sense! I'm moving this to the backlog. Feel free to disagree if it has a higher priority 🙂

**Comment by nikku** [comment]
This is handed through auto-expansion, our standard editor behavior.
