### ISSUE TITLE
Version conflict with `min-dom`

### ISSUE THREAD

**Issue by boris-petrov** [bpmn-io/feel-editor#23]
__Describe the Bug__
Installing `camunda-bpmn-js` (which I think is the "main" package - there's so many of them!) transitively leads to installing `@bpmn-io/feel-editor` `0.4.1` which depends on `min-dom` 4.x. However, all other packages in the dependency tree of `camunda-bpmn-js` depend on `min-dom` 3.x. And when I build my app, my duplicate-package-checker (correctly) warns me that there are multiple versions of that package being bundled. Which is sub-optimal.

__Steps to Reproduce__
Just install `camunda-bpmn-js` in a new repo.

__Expected Behavior__
No duplicate packages.

__Environment__
- Host (Browser/Node version), if applicable: N/A
- OS: Linux
- Library version: 4.0.1

**Comment by nikku** [comment]
All good! Consider any resolution on your end for the moment; we'll step by step migrate our eco-system to new versions of the library, but that takes time.

**Comment by nikku** [comment]
If you want to take a stab at the version bump contribute a PR.
