### ISSUE TITLE
Output variables occassionally are not provided in the autocompletion

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/feel-editor#25]
__Describe the Bug__

Under some circumstances, which are not clearly reproducible, output variables are not suggested in the autocompletion.

__Steps to Reproduce__

See video:

https://user-images.githubusercontent.com/56470362/194881389-164e4599-c959-4cfe-b8dd-556ea6a1c09b.mov

__Expected Behavior__

All output variables should be available, everywhere (or in allowed contexts)

__Environment__

- Camunda Modeler 5.4.1

**Comment by nikku** [comment]
> After switching task flow order, the accessibility of variables must be updated based on how tokens can flow.

We cannot decide such thing / it can generally not be decided "in which direction the token flows". Cf. also inability to decide when inclusive gateway joins.

**Comment by pinussilvestrus** [comment]
I can not reproduce this on my Mac. In the screencast, the `bar` variable of Task 2 is an input variable. When you try to access that in an expression, it won't be visible as only output variables are extracted from the diagram.

![image](https://user-images.githubusercontent.com/9433996/194858436-16372ce5-8f74-4399-af7c-5ef46ae89bd6.png)

![image](https://user-images.githubusercontent.com/9433996/194858560-d6e55241-ce40-4e06-8d5f-139548d5b3ec.png)

As @nikku already stated, the order shouldn't matter at all.

**Comment by christian-konrad** [comment]
@pinussilvestrus my example was dumb. I had a case before with output variables, and tried to reproduce it. Actually, the problem is something else: sometimes, variables are not suggested, and I tried to find a pattern, why.

See this:

https://user-images.githubusercontent.com/56470362/194881389-164e4599-c959-4cfe-b8dd-556ea6a1c09b.mov

I'll update the issue title and description

**Comment by marstamm** [comment]
Hi @christian-konrad ,

from looking at the screen cast, the issue is that `some` is already an internal keyword, as shown by the different Highlight. We only add Suggestions when the node is of type "VariableName". This assumption seems to be to strict to cover all use cases

https://github.com/bpmn-io/feel-editor/blob/main/src/autocompletion/variables.js#L35-L38

Additionally, the suggestions are not updated when using backspace. Same as in https://github.com/camunda/camunda-modeler/issues/3218

**Comment by nikku** [comment]
@marstamm Is this something we want to pick up as part of our current initiative? If not, let's move it to `backlog`.

**Comment by marstamm** [comment]
Let's move it to backlog for now, as it seems to only happen in very specific edge-cases.

However, I will keep it in mind the next time I touch the variable handling and see if it is easy to fix
