### ISSUE TITLE
Variable name starts with $ sign considered as syntax error

### ISSUE THREAD

**Issue by kollerdroid** [bpmn-io/feel-editor#28]
Variable name starts with $ sign considered as syntax error:

<img width="141" alt="image" src="https://user-images.githubusercontent.com/37207139/201686627-45f0c1f4-b0a6-47af-ab83-b1b43580a510.png">

According to [documentation](https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-variables/#variable-names) _**$globalVar**_ is a valid variable name (and Zeebe can resolve it).

If I try to wrap the variable into [backticks](https://camunda.github.io/feel-scala/docs/reference/language-guide/feel-variables/#escape-variable-names), it also considered as syntax error:
 
<img width="141" alt="image" src="https://user-images.githubusercontent.com/37207139/201687001-f40a7ce8-0529-4db6-bf20-e73e01b797de.png">

Do you have a plan to support variable names which starts with $ sign?

**Comment by nikku** [comment]
I may be missreading the DMN spec (page 81, `name start`):

![image](https://user-images.githubusercontent.com/58601/201741459-d538eb85-5070-4f4d-83a2-4593efbd8649.png)

I don't see how `$` is in the list of allowed start chars (but I'll double check this).

We shall accept what is valid FEEL, we _shall not_ necessarily support what is valid FEEL Scala (i.e. custom vendor extensions).

**Comment by marstamm** [comment]
> I don't see how $ is in the list of allowed start chars (but I'll double check this).

The normal `$` unicode is `\u24` which does not appear in the list of allowed characters

**Comment by nikku** [comment]
@kollerdroid Closing this issue as won't fix as `$` is not a valid start char according to the DMN 1.4 spec. I'd suggest you to open an issue in [feel-scala](https://github.com/camunda/feel-scala). Maybe we can get this fixed over there.

**Comment by kollerdroid** [comment]
OK. Thank You @nikku!
