### ISSUE TITLE
Autocompletion for context example data overflows the UI

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/feel-editor#37]
### Describe the Bug

The autocompletion content for context example data overflows the UI, see screenshot

### Steps to Reproduce

1. Add a context with a subcontext as example data 

E.g. 
```
{
    "parsedInvoice":  {
        "invoiceUrl": "https://www.myDMS.com/documents/5983371298572",
        "firstName": "Peter",
        "lastName": "Miller",
        "department": "Sales",
        "billerName": "ACME Corp",
        "billerStreet": "Acme Avenue",
        "billerStreetNo": 1,
        "billerZip": "11111",
        "billerCity": "Acme City",
        "item": "Some product",
        "invoiceValue": 5000,
        "invoiceDate": "2022-12-12",
        "purpose": "Very important for our team"
    }
}
```

3. Use autocompletion in another task for this context
4. Since it auto-removes white spaces and does only break on white spaces, it overflows

<img width="419" alt="Bildschirmfoto 2023-04-17 um 18 14 06" src="https://user-images.githubusercontent.com/56470362/232547051-46876ca8-e11b-4175-888c-823b000d95fc.png">

### Expected Behavior
- Properly format whitespaces in contexts/jsons
- Wrap even if no white spaces

### Environment

- Recent Web Modeler as of April 17th 2023

**Comment by marstamm** [comment]
Let's pick it up in the next iteration
