### ISSUE TITLE
Add option to display gutters

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/feel-editor#41]
### Is your feature request related to a problem? Please describe.

There is currently no option to display gutters in the feel-editor. Here is a sketch for a potential popup editor that comes with gutters.

![image](https://github.com/bpmn-io/feel-editor/assets/9433996/01d8c99f-59d2-49b0-a596-c1b1dafc3b3e)

### Describe the solution you'd like

Add an option to display the gutters, e.g. `showGutters`. 

### Describe alternatives you've considered

Allow providing extensions so implementors can add the [gutters extension](https://codemirror.net/examples/gutter/) on their own.

### Additional context

Code Mirror Gutters: https://codemirror.net/examples/gutter/

**Comment by barmac** [comment]
How about if we allowed to pass custom codemirror extensions instead? This way you could implement whatever useful feature you want without increasing bundle size.
