### ISSUE TITLE
Unable to resolve container

### ISSUE THREAD

**Issue by RC-2023** [bpmn-io/feel-editor#44]
### Describe the Bug

Included  npm install @bpmn-io/feel-editor in my angular app 
error 
No value exists in scope for the shorthand property 'container'. Either declare one or provide an initializer.ts(18004)
(property) container: any
No quick fixes available

### Steps to Reproduce

create new angular app 

```
npm install @bpmn-io/feel-editor 
```

add in `AppComponent.ts` on

``` 
import FeelEditor from '@bpmn-io/feel-editor';
```

```
  ngOnInit() {

    const editor = new FeelEditor({
      container
    });
  }
```
  
it gives error 
No value exists in scope for the shorthand property 'container'. Either declare one or provide an initializer.ts(18004)
(property) container: any
No quick fixes available

### Expected Behavior

no compilation error should occur as its a step mentioned in 
https://github.com/bpmn-io/feel-editor

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Ensure that `container` is actually a declared variable. This looks to me like a usage error.
