### ISSUE TITLE
Allow to provide functions with snippet autocompletion

### ISSUE THREAD

**Issue by barmac** [bpmn-io/feel-editor#50]
### Is your feature request related to a problem? Please describe.

Right now, only built-in functions are provided as snippets in the editor. Even when I pass a function signature via `name` property, it is pasted without a way to provide parameters easily. Also, the type is hardcoded as "variable":

https://github.com/bpmn-io/feel-editor/assets/28307541/34c8a554-86cd-4bf1-a819-2887f048eaaf

### Describe the solution you'd like

* [ ] I can pass a variable of type "function" and see appropriate icon.
* [ ] I can pass `params` next to the function as an array of `{ name: string, type: string }` which are used in a snippet autocompletion.

Example:

```json
{
  "name": "Compute credit score",
  "type": "function",
  "detail": "number",
  "params": [
    {
      "name": "first",
      "type": "Number"
    },
    {
      "name": "second",
      "type": "string"
    }
  ]
}
```

![localhost_9876_debug html](https://github.com/bpmn-io/feel-editor/assets/28307541/5e10ef95-24f2-4a65-99de-6ba13af1bc40)

### Describe alternatives you've considered

One could pass a function signature like it's done with the builtins, but that would be error-prone:

```json
{
  "label": "Compute credit score(first: Number, second: string)",
  "type": "function"
}
```

### Additional context

Required for https://github.com/bpmn-io/dmn-js/issues/827

**Comment by nikku** [comment]
For best utility + potential code analysis we'd want to also offer the return type.

**Comment by barmac** [comment]
Totally! I think this can be still provided via `detail` property.
